-- Drift Auto-Resolution Migration
-- Generated by drift-resolver at 2026-06-11T16:42:03.070795Z
-- Contains 1 automatically resolved safe schema changes
--
-- Changes:
-- 1. Creating a new table does not affect existing data — safe (table: Product)
--
-- Rollback SQL (for reference only — apply manually if needed):
-- 1. DROP TABLE IF EXISTS Product;

CREATE TABLE "Product" ("id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
