from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import os
import sys

try:
	from drift_resolver.models.drift_item import DriftItem
except ModuleNotFoundError:
	project_root = Path(__file__).resolve().parents[2]
	if str(project_root) not in sys.path:
		sys.path.insert(0, str(project_root))
	from drift_resolver.models.drift_item import DriftItem


@dataclass
class MigrationFile:
	"""Represent a generated Prisma migration file on disk."""

	folder_name: str
	folder_path: str
	sql_path: str
	sql_content: str
	item_count: int
	created_at: str


def generate_migration(validated_items: list[DriftItem], migrations_dir: str = "./prisma/migrations") -> MigrationFile:
	"""Write a Prisma migration folder containing the validated drift SQL."""

	resolved_migrations_dir = _validate_migrations_dir(migrations_dir)
	now_utc = datetime.now(timezone.utc)
	timestamp = now_utc.strftime("%Y%m%d%H%M%S")
	created_at = now_utc.isoformat().replace("+00:00", "Z")
	folder_name = f"{timestamp}_drift_auto_resolve"
	folder_path = os.path.join(resolved_migrations_dir, folder_name)
	sql_path = os.path.join(folder_path, "migration.sql")

	print(f"[GENERATOR] Creating migration: {folder_name}")
	os.makedirs(folder_path, exist_ok=True)

	sql_content = _build_migration_sql(validated_items)
	with open(sql_path, "w", encoding="utf-8") as file_handle:
		file_handle.write(sql_content)

	print(f"[GENERATOR] Migration contains {len(validated_items)} statements.")
	print(f"[GENERATOR] Written to: {sql_path}")

	return MigrationFile(
		folder_name=folder_name,
		folder_path=folder_path,
		sql_path=sql_path,
		sql_content=sql_content,
		item_count=len(validated_items),
		created_at=created_at,
	)


def _build_migration_sql(items: list[DriftItem]) -> str:
	"""Build the full migration.sql content for the validated drift items."""

	timestamp = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
	lines: list[str] = []
	lines.append("-- Drift Auto-Resolution Migration")
	lines.append(f"-- Generated by drift-resolver at {timestamp}")
	lines.append(f"-- Contains {len(items)} automatically resolved safe schema changes")
	lines.append("--")
	lines.append("-- Changes:")

	for index, item in enumerate(items, start=1):
		table_name = item.table_name or "unknown table"
		lines.append(f"-- {index}. {item.reason} (table: {table_name})")

	lines.append("--")
	lines.append("-- Rollback SQL (for reference only — apply manually if needed):")
	for index, item in enumerate(items, start=1):
		rollback_sql = item.rollback_sql or "No rollback available"
		lines.append(f"-- {index}. {rollback_sql}")
	lines.append("")

	for index, item in enumerate(items):
		sql_statement = item.sql.strip()
		if not sql_statement.endswith(";"):
			sql_statement += ";"
		lines.append(sql_statement)
		if index < len(items) - 1:
			lines.append("")

	return "\n".join(lines) + "\n"


def _validate_migrations_dir(migrations_dir: str) -> str:
	"""Ensure the Prisma migrations directory exists before writing a migration."""

	resolved_path = os.path.abspath(migrations_dir)
	if not os.path.isdir(resolved_path):
		raise FileNotFoundError(
			f"Migrations directory not found: {resolved_path}. \n"
			"Make sure you are running from the project root and \n"
			"prisma/migrations/ exists."
		)

	return resolved_path


def get_migration_preview(validated_items: list[DriftItem]) -> str:
	"""Return a preview of the migration content without writing any files."""

	return _build_migration_sql(validated_items)


if __name__ == "__main__":
	"""Generate a sample migration file when the module is executed directly."""

	demo_items = [
		DriftItem(
			sql='ALTER TABLE "users" ADD COLUMN "bio" TEXT',
			statement_type="AlterTable_Add",
			table_name="users",
			column_name="bio",
			rollback_sql='ALTER TABLE users DROP COLUMN bio;',
			reason="Adding a nullable column is safe",
		),
		DriftItem(
			sql='CREATE INDEX "idx_users_email" ON "users"("email")',
			statement_type="CreateIndex",
			table_name="users",
			column_name=None,
			rollback_sql='DROP INDEX IF EXISTS idx_users_email;',
			reason="Creating an index is safe",
		),
	]

	result = generate_migration(demo_items, migrations_dir="./prisma/migrations")
	print(result)
	print()
	print("[GENERATOR] migration.sql contents:")
	print(result.sql_content)
