-- Drift Auto-Resolution Migration
-- Generated by drift-resolver at 2026-05-29T16:55:17.297729Z
-- Contains 2 automatically resolved safe schema changes
--
-- Changes:
-- 1. Adding a nullable column is safe (table: users)
-- 2. Creating an index is safe (table: users)
--
-- Rollback SQL (for reference only — apply manually if needed):
-- 1. ALTER TABLE users DROP COLUMN bio;
-- 2. DROP INDEX IF EXISTS idx_users_email;

ALTER TABLE "users" ADD COLUMN "bio" TEXT;

CREATE INDEX "idx_users_email" ON "users"("email");
