-- Drift Auto-Resolution Migration
-- Generated by drift-resolver at 2026-06-06T17:56:42.743658Z
-- Contains 1 automatically resolved safe schema changes
--
-- Changes:
-- 1. Dropping an index does not affect data — safe but monitor query performance (table: idx_user_email)
--
-- Rollback SQL (for reference only — apply manually if needed):
-- 1. No rollback available

DROP INDEX "idx_user_email";
